{% set name = "strictyaml" %}
{% set version = "1.0.1" %}
{% set sha256 = "06d7100587695a0edfabd772a6c6fb69071fc38c413df599e22dfd40e52f5fad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ruamel.yaml >=0.14.2
    - python-dateutil >=2.6.0

test:
  imports:
    - strictyaml

about:
  home: http://hitchdev.com/strictyaml/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Type-safe YAML parser and validator.'
  dev_url: https://github.com/crdoconnor/strictyaml

extra:
  recipe-maintainers:
    - mcs07
