travis:
  secure:
    BINSTAR_TOKEN: VVXU9/WZxIOaVjsnvyjPyKFJuajHmVGKaQTc38qmw9Po84vxD4tTfId5aoIdxE9+nSne9Aw3GBhjV3xrkFH2xmRKhC3bHdHQN5NHH9zMPWwRrsozMmGoAhiVQLmWCaLXQ0tFOgdxm6AA8d5Ge6IvnesgGYeFV5lqLaDM+okyGgH4OXJQQ9llXjEsooc9/DzeDY2Xk4PjDugp5LpEKM9sxtBoZhGX/nms9dfim6cPLaKDEoDcztdtYmOvT4FXo+LTdG5jfQJZUSVU61VYkHkDS4mJuxKECJrBqUf8EJumbzmzbg9ybDOtyvTMZjhhieVf/kesUuNXUdUCOsgYaU0Kw1g6IaQip1wOZtK1NHDLMa9cI4zwFNJHc21JGboIOXMGZVo1rLLN0kKjUkG8A8Y9WGo7a9V+MqGWeaqKM1FEkmXPPmyWutbX2xwc+Ft03jtk0KgNdXkeomKhRluIh5rkw7HmCaXgsOiFZikBK77Th2pDW9Q6WAudSrVIpSvWflGpqlfWAC9TEn85wRhQsSPmKmxPGUPGdGhjGUzgW0/pKNI9AF1EPOEccWnhYMhNi0eMUzcLznXJwSTX4b+Gkk9bn2KcP4GSjVPIj3VS2mA/p69gvJ6emsae0JWUnDDM7OGtZbCt+B/ZhCvmevVQLvJbSk+7dc0KusheaL5EHY4BCow=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
