travis:
  secure:
    BINSTAR_TOKEN: J5TDW900MKQwrnOBkaGuas8bipLTRJMFisvediCBjQsviNNx2gNmrabED2S+mwmDiq+Ko1TNVYWsMzcx78rEB2DtS7ZFP8S+FJRc25j/eIis9glVrMXUTi7ywH5H27TeJgTm195UqSFXdEgpJABoG6Odfn+bYPXkBhyYJFBAEPHNvBrIt5LPutWrAM6bkTw0eYazJoHT/vb/q33/sksSAAP7MIuA9gK9S4hk1QFFnUlzhhF1B/SPEAXRvLtUmFAy8hMkZ56kTkHyQMKZ9fTFb0HJhsFhoiple7KK+Jyjs2YmILp8XLrg+ArXVtP0RmmnTJdSm/xZt4TpVPwvVjKoKRA96IY07vWn3+L9VhxWLu+MYVMCZYTbF8JYPhBVHdEIwM0MqrJW5gTTZy8pS5b2cjrwNnhPyfED1B1SZYH4DXti+ZqHPb6mMV8hFUJ8sIs8IjtKDsBEQRXlCISj3vOqS6Jjemn5R59EXxeio8pF7OR07WGv22LJ+fl6ACkfONbNHrbzd78NaNbX/Vgpg/2RZxddbvTOYFFCpZ3oV4he8HQMbswPVHA9mUq1WRUztU9Wk1fkC60lo1OEdYyxXKXDRKWymSvZy9NHcXwXuCengqm7mLdquAd8FxvTQdcN+02Tf4cqUz2P5STI92oDqlUDCXdW7/31T+5uB+vcbtTwiNo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
